### ISSUE TITLE
What to do with packages that require only some files of a dependency

### ISSUE THREAD

**Issue by sebamarynissen** [memo33/sc4pac#40]
As I was adding metadata in #39, I've stumbled upon the following situation. Sometimes a package lists only certain files of another package as a dependency. Typically this happens with `.SC4Model` files that are needed, but not the `.SC4Lot` files. My question is what the recommended approach is in this case.

If I list the dependency package explicitly like
```yaml
group: bob
name: some-package
dependencies:
  - alice:some-package
```
then all files end up in the Plugins folder, even the lots that the user might not want to install.

However, if I use the asset instead like
```yaml
group: bob
name: some-package
assets:
 - assetId: alice-some-package
   include: alice.SC4Model
```
then if the user decides to explictly install `alice:some-package` later on, then we end up with two copies of `alice.SC4Model`: one in `alice.some-package.1.0.sc4pac` and one in `bob.some-package.1.0.sc4pac`. As those two files are identical, it doesn't really matter that there are two files, so can I assume that this is the recommended approach?

Ideally sc4pac would handle this somehow by allowing `include/exclude` on dependencies as well or something, but I don't know if it's worth it.
